param([string]$Output='public')
$ErrorActionPreference='Stop'
$root=if($PSScriptRoot){$PSScriptRoot}else{(Get-Location).Path}
$cfg=Get-Content (Join-Path $root 'site/config.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$data=Get-Content (Join-Path $root 'site/content.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$out=Join-Path $root $Output
$utf8=New-Object System.Text.UTF8Encoding($false)
function Write-Generated($path,$text){$full=Join-Path $out $path;[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($full))|Out-Null;[IO.File]::WriteAllText($full,$text,$utf8)}
function Esc($text){[System.Net.WebUtility]::HtmlEncode([string]$text)}
function Link($slug){$cfg.basePath+'/'+$slug}
function Url($slug){$cfg.url.TrimEnd('/')+$cfg.basePath+'/'+$slug}
function Json($value){ConvertTo-Json -InputObject $value -Depth 25 -Compress}
function ContactDetails{
 $phones=if($cfg.phones){@($cfg.phones)}elseif($cfg.phone){@($cfg.phone)}else{@()}
 $links=@($phones|ForEach-Object{"<a href='tel:$($_ -replace '[^+0-9]','')'>$(Esc $_)</a>"})
 $phoneText=if($links.Count){$links -join '; '}else{'[УКАЗАТЬ ДАННЫЕ]'}
 $emailText=if($cfg.email){"<a href='mailto:$(Esc $cfg.email)'>$(Esc $cfg.email)</a>"}else{'[УКАЗАТЬ ДАННЫЕ]'}
 $addressText=if($cfg.address){"<br>Адрес: <strong>$(Esc $cfg.address)</strong>"}else{''}
 $mapText=if($cfg.mapUrl){"<br><a href='$(Esc $cfg.mapUrl)' target='_blank' rel='noopener'>Ступино — Яндекс Карты</a>"}else{''}
 return "Телефон: $phoneText<br>Email: $emailText<br>Регион: $(Esc $cfg.region)$addressText$mapText"
}
function Video($id,$title){$t=Esc $title;return "<figure class='media'><a href='https://www.youtube.com/watch?v=$id' target='_blank' rel='noopener'><img src='https://i.ytimg.com/vi/$id/hqdefault.jpg' width='480' height='360' loading='lazy' alt='$t'></a><figcaption>$t · <a href='https://www.youtube.com/watch?v=$id'>Смотреть на YouTube</a></figcaption></figure>"}
function Faq($items){$html="<section class='faq' id='faq'><h2>Частые вопросы</h2>";foreach($i in $items){$html+="<details><summary>$(Esc $i.q)</summary><p>$(Esc $i.a)</p></details>"};return $html+'</section>'}
function Contact{ @"
<section class='band' id='contact'><div class='wrap contact-grid'><div><h2>Обсудить строительство</h2><p>Тип дома, участок и состав работ помогут подготовить запрос на расчет.</p><p>Телефон: $(if($cfg.phone){Esc $cfg.phone}else{'[УКАЗАТЬ ДАННЫЕ]'})<br>Email: $(if($cfg.email){Esc $cfg.email}else{'[УКАЗАТЬ ДАННЫЕ]'})<br>Регион: $(Esc $cfg.region)</p><a href='$(Esc $cfg.channel)'>YouTube-канал</a></div><form data-email='$(Esc $cfg.email)'><div class='form-grid'><label>Имя<input name='name' autocomplete='name' maxlength='100' required></label><label>Телефон или удобный способ связи<input name='contact' autocomplete='tel' maxlength='150' required></label><label>Тип дома<select name='type'><option>Барнхаус</option><option>Каркасный дом</option><option>Пока выбираю</option></select></label><label>Примерная площадь, м²<input name='area' type='number' min='1' max='5000' step='any'></label></div><label>Комментарий<textarea name='comment' rows='3' maxlength='3000'></textarea></label><label class='consent'><input type='checkbox' required name='consent'> <span>Согласен на обработку данных по <a href='$(Link 'consent/')'>условиям согласия</a></span></label><button class='btn' type='submit'>Подготовить запрос на расчет</button><output id='form-status' aria-live='polite'></output><pre id='request-preview' hidden></pre><a id='send-email' class='btn' hidden>Открыть почтовое приложение</a></form></div></section>
"@ }
function Objects{ $html="<div class='filters'><label>Тип дома<select id='type'><option value='all'>Все типы</option><option value='barnhaus'>Барнхаус</option><option value='karkas'>Каркасный дом</option></select></label><label>Этажность<select id='floors'><option value='all'>Все, включая неуказанные</option><option value='1'>Один этаж</option><option value='2'>Два этажа</option></select></label><label>Площадь<select id='area'><option value='all'>Любая, включая неуказанную</option><option value='small'>Менее 100 м²</option><option value='large'>От 100 м²</option></select></label></div><p id='result-count' role='status'>Найдено объектов: $($data.objects.Count)</p><div class='grid two'>";foreach($o in $data.objects){$objectImage=if($o.id -eq 'J3FnB9bFLVo'){"$(Link 'assets/barnhaus-8-9x13-5.jpg')"}else{"https://i.ytimg.com/vi/$($o.id)/hqdefault.jpg"};$html+="<article class='item' data-object data-type='$($o.type)' data-area='$($o.area)' data-floors='$($o.floors)'><a class='cover' href='https://www.youtube.com/watch?v=$($o.id)'><img src='$objectImage' width='480' height='360' loading='lazy' alt='$(Esc $o.name) — фото объекта на этапе строительства'></a><div class='copy'><h3>$(Esc $o.name)</h3><p>$(Esc $o.description)</p><p>Площадь: [УКАЗАТЬ ДАННЫЕ]<br>Этажность: [УКАЗАТЬ ДАННЫЕ]<br>Планировка и комплектация: [УКАЗАТЬ ДАННЫЕ]</p><a href='https://www.youtube.com/watch?v=$($o.id)'>Посмотреть этап строительства</a></div></article>"};return $html+"</div><p id='empty' class='empty' hidden>Нет объектов с подтвержденными характеристиками для выбранных фильтров.</p>" }
function Cards($items,$prefix){$html="<div class='grid'>";foreach($i in $items){$image='';if($i.slug -eq 'barnhaus' -and !$prefix){$image="<a class='card-photo' href='$(Link 'barnhaus/')'><img src='$(Link 'assets/barnhaus-8-9x13-5.jpg')' width='968' height='544' loading='lazy' alt='Каркасный барнхаус 8,9×13,5 на этапе строительства'></a>"}elseif($i.video){$image="<a class='card-photo' href='$(Link ($prefix+$i.slug+'/'))'><img src='https://i.ytimg.com/vi/$($i.video)/hqdefault.jpg' width='480' height='360' loading='lazy' alt='$(Esc $i.title) — кадр видео канала'></a>"};$html+="<article class='plain'>$image<h3><a href='$(Link ($prefix+$i.slug+'/'))'>$(Esc $i.title)</a></h3><p>$(Esc $i.intro)</p></article>"};return $html+'</div>'}
$script:urls=@()
function Page($slug,$title,$desc,$body,$faq=@(),$kind='WebPage',$videoId=''){
 $canonical=Url $slug;$rootLink=Link '';$og=Url ('assets/og/'+$(if($slug){$slug.TrimEnd('/').Replace('/','-')}else{'home'})+'.png')
 $schema=@(@{'@type'='Organization';'@id'=(Url '')+'#organization';name=$cfg.name;url=(Url '');sameAs=@($cfg.channel)},@{'@type'='WebSite';'@id'=(Url '')+'#website';name=$cfg.name;url=(Url '');inLanguage='ru-RU'},@{'@type'='WebPage';name=$title;description=$desc;url=$canonical;inLanguage='ru-RU';isPartOf=@{'@id'=(Url '')+'#website'}},@{'@type'='ImageObject';contentUrl=$og;caption=$title;width=1200;height=630})
 $crumb='';if($slug){$crumb="<div class='wrap breadcrumbs'><a href='$rootLink'>Главная</a><span>/</span><span>$(Esc $title)</span></div>";$schema+=@{'@type'='BreadcrumbList';itemListElement=@(@{'@type'='ListItem';position=1;name='Главная';item=(Url '')},@{'@type'='ListItem';position=2;name=$title;item=$canonical})}}
 if($kind -eq 'Article'){$schema+=@{'@type'='Article';headline=$title;description=$desc;url=$canonical;image=$og;inLanguage='ru-RU';articleBody=([regex]::Replace($body,'<[^>]+>',' ') -replace '\s+',' ').Trim()}}
 if($kind -eq 'Service'){$schema+=@{'@type'='Service';name=$title;description=$desc;url=$canonical}}
 if($faq.Count){$questions=@();foreach($f in $faq){$questions+=@{'@type'='Question';name=$f.q;acceptedAnswer=@{'@type'='Answer';text=$f.a}}};$schema+=@{'@type'='FAQPage';mainEntity=$questions}}
 if($cfg.email){$schema[0].email=$cfg.email}
 if($cfg.phones){$schema[0].telephone=@($cfg.phones)}elseif($cfg.phone){$schema[0].telephone=$cfg.phone}
 if($cfg.address){$schema[0].address=@{'@type'='PostalAddress';addressLocality='Ступино';addressRegion='Московская область';addressCountry='RU'}}
 $json=Json @{'@context'='https://schema.org';'@graph'=$schema}
 $articleMeta=if($kind -eq 'Article'){"<meta property='og:type' content='article'>"}else{"<meta property='og:type' content='website'>"}
 $html=@"
<!doctype html><html lang='ru'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'><title>$(Esc $title) | $(Esc $cfg.name)</title><meta name='description' content='$(Esc $desc)'><link rel='canonical' href='$canonical'><meta name='theme-color' content='#294f3d'><meta property='og:title' content='$(Esc $title)'><meta property='og:description' content='$(Esc $desc)'>$articleMeta<meta property='og:url' content='$canonical'><meta property='og:image' content='$og'><meta property='og:image:width' content='1200'><meta property='og:image:height' content='630'><meta property='og:site_name' content='$(Esc $cfg.name)'><meta property='og:locale' content='ru_RU'><meta name='twitter:card' content='summary_large_image'><meta name='twitter:title' content='$(Esc $title)'><meta name='twitter:description' content='$(Esc $desc)'><meta name='twitter:image' content='$og'><link rel='stylesheet' href='$(Link 'assets/styles.css')'><script src='$(Link 'assets/app.js')' defer></script><script type='application/ld+json'>$json</script></head><body><a class='skip btn' href='#main'>К содержанию</a><header><div class='wrap header-inner'><a class='brand' href='$rootLink'>$(Esc $cfg.name)<small>Каркасные дома · Барнхаусы</small></a><button class='menu' aria-label='Меню' aria-expanded='false' aria-controls='navigation'><svg viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' aria-hidden='true'><path d='M4 6h16M4 12h16M4 18h16'/></svg></button><nav id='navigation' aria-label='Основная навигация'><a href='$(Link 'barnhaus/')'>Барнхаусы</a><a href='$(Link 'karkasnye-doma/')'>Каркасные дома</a><a href='$(Link 'proekty-domov/')'>Объекты</a><a href='$(Link 'ceny/')'>Стоимость</a><a href='$(Link 'blog/')'>Блог</a><a href='#contact'>Консультация</a></nav></div></header>$crumb<main id='main'>$body$(Contact)</main><footer><div class='wrap grid'><div><h3>$(Esc $cfg.name)</h3><p>Материалы о каркасном строительстве и барнхаусах.</p><p>Регион: $(Esc $cfg.region)<br>Телефон: [УКАЗАТЬ ДАННЫЕ]<br>Email: [УКАЗАТЬ ДАННЫЕ]<br>Мессенджеры и соцсети: [УКАЗАТЬ ДАННЫЕ]<br>Реквизиты: [УКАЗАТЬ ДАННЫЕ]</p><a href='$(Esc $cfg.channel)'>YouTube</a></div><div><h3>Строительство</h3><ul>$(($data.services | ForEach-Object {"<li><a href='$(Link ($_.slug+'/'))'>$(Esc $_.title)</a></li>"}) -join '')</ul></div><div><h3>Полезное</h3><ul><li><a href='$(Link 'blog/')'>Все статьи</a></li><li><a href='$(Link 'proekty-domov/')'>Объекты и видео</a></li><li><a href='#faq'>Вопросы и ответы</a></li></ul></div><div><h3>Документы</h3><ul><li><a href='$(Link 'privacy/')'>Политика конфиденциальности</a></li><li><a href='$(Link 'consent/')'>Согласие на обработку данных</a></li></ul><p>Цены, сроки и комплектации требуют подтверждения. Название использовано по YouTube-каналу.</p></div></div></footer></body></html>
"@
 $oldContacts="Телефон: $(if($cfg.phone){Esc $cfg.phone}else{'[УКАЗАТЬ ДАННЫЕ]'})<br>Email: $(if($cfg.email){Esc $cfg.email}else{'[УКАЗАТЬ ДАННЫЕ]'})<br>Регион: $(Esc $cfg.region)"
 $oldFooter="Регион: $(Esc $cfg.region)<br>Телефон: $(if($cfg.phone){Esc $cfg.phone}else{'[УКАЗАТЬ ДАННЫЕ]'})<br>Email: $(if($cfg.email){Esc $cfg.email}else{'[УКАЗАТЬ ДАННЫЕ]'})"
 $html=$html.Replace($oldContacts,(ContactDetails)).Replace($oldFooter,(ContactDetails))
 $html=$html.Replace("Регион: $(Esc $cfg.region)<br>Телефон: [УКАЗАТЬ ДАННЫЕ]<br>Email: [УКАЗАТЬ ДАННЫЕ]",(ContactDetails))
 $html=$html.Replace('<body>',"<body><div class='topline'><div class='wrap'><span>Каркасные дома · Барнхаусы</span><a href='$(Esc $cfg.channel)'>Работы и разборы на YouTube</a></div></div>")
  $html=$html.Replace("<meta name='theme-color' content='#294f3d'>","<meta name='theme-color' content='#ffd21f'>")
  $headerContact="<div class='header-contact'><a href='tel:$($cfg.phone -replace '[^+0-9]','')'>$(Esc $cfg.phone)</a><a href='#contact'>Обсудить проект →</a></div>"
  $html=$html.Replace("</nav></div></header>","</nav>$headerContact</div></header>")
  $html=$html.Replace("<label>Комментарий<textarea", "<label>Ссылка на проект<input name='project' type='url' placeholder='https://' maxlength='1000'></label><label>Комментарий<textarea")
  $html=$html.Replace("<button class='btn' type='submit'>", "<input type='hidden' name='selection'><button class='btn' type='submit'>")
  $html=$html.Replace("</body>","<dialog id='photo-dialog' aria-label='Просмотр фотографии'><button type='button' class='dialog-close' title='Закрыть' aria-label='Закрыть'>×</button><img alt=''><p></p></dialog><dialog id='compare-dialog' aria-labelledby='compare-title'><button type='button' class='dialog-close' title='Закрыть' aria-label='Закрыть'>×</button><h2 id='compare-title'>Сравнение объектов</h2><div id='compare-content'></div></dialog><div class='quick-contact'><a href='tel:$($cfg.phone -replace '[^+0-9]','')' aria-label='Позвонить'>Позвонить</a><a href='#contact'>Запросить смету →</a></div></body>")
  Write-Generated $(if($slug){$slug+'index.html'}else{'index.html'}) $html
 $script:urls+=$canonical
 # Generate an independent 1200x630 social image for every page.
 $bitmap=New-Object Drawing.Bitmap -ArgumentList 1200,630;$g=[Drawing.Graphics]::FromImage($bitmap);$g.Clear([Drawing.Color]::FromArgb(232,238,233));$brush=New-Object Drawing.SolidBrush -ArgumentList ([Drawing.Color]::FromArgb(41,79,61));$g.FillRectangle($brush,0,0,24,630);$font1=New-Object Drawing.Font -ArgumentList 'Arial',24;$font2=New-Object Drawing.Font -ArgumentList 'Arial',42,([Drawing.FontStyle]::Bold);$font3=New-Object Drawing.Font -ArgumentList 'Arial',20;$rect=New-Object Drawing.RectangleF -ArgumentList 60,180,1080,300;$g.DrawString($cfg.name,$font1,[Drawing.Brushes]::DarkSlateGray,60,60);$g.DrawString($title,$font2,[Drawing.Brushes]::Black,$rect);$g.DrawString('Каркасные дома / Барнхаусы / Этапы строительства',$font3,[Drawing.Brushes]::DarkSlateGray,60,540);$imagePath=Join-Path $out ('assets/og/'+$(if($slug){$slug.TrimEnd('/').Replace('/','-')}else{'home'})+'.png');[IO.Directory]::CreateDirectory([IO.Path]::GetDirectoryName($imagePath))|Out-Null;$bitmap.Save($imagePath,[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bitmap.Dispose()
}
Add-Type -AssemblyName System.Drawing
$requestHint=if($cfg.email){'Подготовьте проект, сведения об участке и перечень работ. Форма составит письмо для самостоятельной отправки через почтовое приложение.'}else{'Подготовьте проект, сведения об участке и перечень работ. Получатель заявки пока требует подключения.'}
$faq=@(@{q='Как получить стоимость дома?';a='Подтвержденного прайса нет. Подготовьте проект, сведения об участке и перечень работ. Получатель заявки пока требует подключения.'},@{q='Где посмотреть реальные этапы?';a='На YouTube-канале опубликованы серии по барнхаусу 8,9×13,5 и каркасному дому 9,5×12. Ссылки приведены в каталоге и статьях.'},@{q='Какие сроки и комплектации доступны?';a='Подтвержденные сроки, состав комплектаций и коммерческие условия: [УКАЗАТЬ ДАННЫЕ].'})
$faq[0].a='Подтвержденного прайса нет. '+$requestHint
$landing=@"
<section class='hero'><img src='https://i.ytimg.com/vi/J3FnB9bFLVo/hqdefault.jpg' width='480' height='360' fetchpriority='high' alt='Сборка стен барнхауса 8,9×13,5 — кадр видео канала'><div class='wrap'><div class='eyebrow'>Всё правильно, всё сходится!</div><h1>Строительство каркасных домов и барнхаусов</h1><p>От платформы до фасада. Реальные этапы, материалы и узлы из видео канала — для осознанного выбора будущего дома.</p><div class='actions'><a class='btn light' href='#contact'>Рассчитать стоимость</a><a class='btn light' href='$(Link 'proekty-domov/')'>Посмотреть проекты</a></div></div></section><section><div class='wrap'><h2>Сначала разберемся в деталях</h2><div class='grid'><div class='plain'><h3>Работы на видео</h3><p>Сборка стен, утепление платформы, мембрана и фасад доступны в сериях канала.</p></div><div class='plain'><h3>Материалы и узлы</h3><p>В названиях роликов встречаются ОСП, сайдинг Grand Line и профлист Stinergy СТ15.</p></div><div class='plain'><h3>Расчет по задаче</h3><p>Площадь и перечень работ обсуждаются вместе. Подтвержденный прайс: [УКАЗАТЬ ДАННЫЕ].</p></div></div></div></section><section class='band'><div class='wrap'><h2>Направления строительства</h2>$(Cards ($data.services | Select-Object -First 7) '')</div></section><section><div class='wrap'><h2>Объекты из серий канала</h2>$(Objects)</div></section><section class='band'><div class='wrap'><h2>Этапы: что можно изучить на канале</h2><ol class='steps'><li>Обвязка, лаги и платформа</li><li>Сборка стен и перегородок</li><li>Балка и стропила</li><li>Мембрана, обрешетка и фасад</li></ol><a href='$(Link 'stroitelstvo-doma/')'>Обсудить состав работ</a></div></section><section><div class='wrap'><h2>Видео с объектов</h2><div class='grid'>$(($data.videos|ForEach-Object{Video $_.id $_.title}) -join '')</div></div></section><section class='band'><div class='wrap'><h2>Что влияет на расчет</h2><p>Проект, участок, комплект материалов, доставка и объем работ. Цену без подтвержденной сметы не указываем.</p><a class='btn' href='$(Link 'ceny/')'>Посмотреть комплектации</a></div></section><section><div class='wrap'><h2>Читайте также</h2>$(Cards ($data.articles|Select-Object -First 3) 'blog/')$(Faq $faq)</div></section>
"@
$landing=$landing.Replace('От платформы до фасада. Реальные этапы, материалы и узлы из видео канала — для осознанного выбора будущего дома.','От платформы до фасада — реальные этапы строительства, материалы и узлы, чтобы вы осознанно выбирали будущий дом.')
$landing=$landing.Replace('https://i.ytimg.com/vi/J3FnB9bFLVo/hqdefault.jpg',"$(Link 'assets/barnhaus-8-9x13-5.jpg')")
$landing=$landing.Replace('Сборка стен барнхауса 8,9×13,5 — кадр видео канала','Барнхаус 8,9×13,5 на этапе строительства')
$selection=(Get-Content (Join-Path $root 'site/selection.html') -Raw -Encoding UTF8).Replace('{{BASE}}', (Link ''))
$landing=$landing.Replace("<section><div class='wrap'><h2>Сначала разберемся в деталях</h2>", $selection+"<section><div class='wrap'><h2>Сначала разберемся в деталях</h2>")
$gallery="<section class='visual-strip'><div class='wrap'><div class='visual-grid'><figure><img src='$(Link 'assets/frame.jpg')' width='480' height='360' loading='lazy' alt='Сборка стен барнхауса на объекте'><figcaption>Каркас и стены</figcaption></figure><figure><img src='$(Link 'assets/roof.jpg')' width='480' height='360' loading='lazy' alt='Балка и стропила барнхауса'><figcaption>Кровля и стропила</figcaption></figure><figure><img src='$(Link 'assets/facade.jpg')' width='480' height='360' loading='lazy' alt='Обрешетка и профлист на фасаде'><figcaption>Фасад и обрешетка</figcaption></figure></div></div></section>"
$landing=$landing.Replace("<section><div class='wrap'><h2>Сначала разберемся в деталях</h2>",$gallery+"<section><div class='wrap'><h2>Сначала разберемся в деталях</h2>")
Page '' 'Строительство каркасных домов и барнхаусов' 'Реальные этапы строительства барнхаусов и каркасных домов: видео, материалы, вопросы к смете и запрос на расчет.' $landing $faq
foreach($s in $data.services){
 $desc=$s.intro;$body="<section class='page-head'><div class='wrap'><h1>$(Esc $s.title)</h1><p class='lead'>$(Esc $s.intro)</p><div class='actions'><a class='btn' href='#contact'>Получить консультацию</a><a class='btn secondary' href='$(Link 'proekty-domov/')'>Подобрать проект</a></div></div></section><section class='band'><div class='wrap'><h2>Что обсудить перед выбором</h2><p>$(Esc $s.focus)</p><h3>Комплектации и состав работ</h3><div class='table-scroll'><table><thead><tr><th>Этап расчета</th><th>Что уточнить</th><th>Предложение компании</th></tr></thead><tbody><tr><td>Конструкции</td><td>Основание, каркас, кровля</td><td>[УКАЗАТЬ ДАННЫЕ]</td></tr><tr><td>Теплый контур</td><td>Утепление, мембраны, окна, двери</td><td>[УКАЗАТЬ ДАННЫЕ]</td></tr><tr><td>Под ключ</td><td>Инженерия, отделка и исключения</td><td>[УКАЗАТЬ ДАННЫЕ]</td></tr></tbody></table></div><p>Эта таблица — перечень для обсуждения, а не утвержденные комплектации компании.</p></div></section><section><div class='wrap'><h2>Этапы, сроки и стоимость</h2><ol class='steps'><li>Подготовить задание и сведения об участке</li><li>Уточнить проект, состав материалов и работ</li><li>Запросить смету, график и порядок приемки</li><li>Согласовать условия договора</li></ol><p>Сроки и стоимость по выбранному проекту: [УКАЗАТЬ ДАННЫЕ].</p><h2>Реальные этапы на видео</h2>$(Video $s.video $s.title)<h2>Связанные объекты</h2>$(Objects)$(Faq $faq)<h2>Читайте также</h2>$(Cards ($data.articles|Where-Object{$_.service -eq $s.slug}) 'blog/')<div class='longlinks'><a href='$(Link 'ceny/')'>Стоимость и состав расчета</a><a href='$(Link 'individualnyj-proekt/')'>Индивидуальное задание</a><a href='$(Link 'blog/')'>Блог о строительстве</a></div></div></section>";
  $photo="<figure class='house-banner'><img src='$(Link 'assets/timber-house.jpg')' width='3224' height='2304' loading='lazy' alt='Готовый каркасный дом в Верхней Савойе, Франция'><figcaption>Иллюстрация каркасного дома. © Yann Forget / <a href='https://commons.wikimedia.org/wiki/File:Timber-framed_villa,_Haute-Savoie,_France.jpg'>Wikimedia Commons</a> / <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a>. Отображение адаптировано по размеру.</figcaption></figure><p><a class='btn secondary' href='https://www.youtube.com/watch?v=$($s.video)'>Смотреть этап строительства на YouTube</a></p>"
  $body=$body.Replace((Video $s.video $s.title),$photo)
  Page ($s.slug+'/') $s.title $desc $body $faq 'Service'
}
foreach($a in $data.articles){
 $afaq=@(@{q='Подтверждает ли видео параметры моего дома?';a='Нет. Видео относится к конкретному этапу объекта канала. Параметры вашего дома нужно согласовать в проекте и документах.'},@{q='Какие данные нужны для консультации?';a=$a.check.Replace('|',', ')+'.'})
 $rows='';$items='';foreach($checkItem in $a.check.Split('|')){$safe=Esc $checkItem;$rows+="<tr><td>$safe</td><td>Запросить документ или пояснение по вашему проекту</td></tr>";$items+="<li>$safe</li>"}
 $related=$data.articles|Where-Object{$_.slug -ne $a.slug}|Select-Object -First 2;$body="<div class='wrap article'><section class='page-head'><h1>$(Esc $a.title)</h1><p class='lead'>$(Esc $a.intro)</p><p class='note'>Материал основан на названиях и темах видео канала. Даты публикации и обновления материала: [УКАЗАТЬ ДАННЫЕ].</p><div class='toc'><b>Содержание</b><ol><li><a href='#topic'>$(Esc $a.heading)</a></li><li><a href='#check'>Что уточнить</a></li><li><a href='#video'>Видео по теме</a></li><li><a href='#faq'>Вопросы и ответы</a></li></ol></div></section><section id='topic'><h2>$(Esc $a.heading)</h2><p>$(Esc $a.body)</p><h3>Исходные данные</h3><ul>$items</ul></section><section id='check'><h2>Что уточнить по своему проекту</h2><div class='table-scroll'><table><thead><tr><th>Вопрос</th><th>Следующий шаг</th></tr></thead><tbody>$rows</tbody></table></div></section><section id='video'><h2>Видео по теме</h2>$(Video $a.video $a.heading)<p>Источник: <a href='https://www.youtube.com/watch?v=$($a.video)'>ролик YouTube-канала</a>. Числовые параметры, не подтвержденные источником, не добавлены.</p><a class='btn' href='$(Link ($a.service+'/'))'>Обсудить проект и расчет</a></section>$(Faq $afaq)<section><h2>Читайте также</h2>$(Cards $related 'blog/')</section></div>"
 Page ('blog/'+$a.slug+'/') $a.title $a.intro $body $afaq 'Article'
}
Page 'blog/' 'Блог о каркасных домах и барнхаусах' 'Материалы по темам YouTube-канала: проект, утепление, фасад, этапы строительства и вопросы к расчету.' "<section><div class='wrap'><h1>Блог о строительстве</h1><p>Видео, проверяемые вопросы и материалы для выбора дома.</p>$(Cards $data.articles 'blog/')$(Faq $faq)</div></section>" $faq
foreach($legal in @('privacy','consent')){$title=if($legal -eq 'privacy'){'Политика конфиденциальности'}else{'Согласие на обработку данных'};Page ($legal+'/') $title 'Сведения о работе формы и полях, требующих заполнения владельцем сайта.' "<section><div class='wrap article'><h1>$title</h1><p>Оператор персональных данных, реквизиты, контакт для обращений: [УКАЗАТЬ ДАННЫЕ].</p><p>Текущая форма составляет текст в браузере. Без подключенного email или CRM запрос не отправляется. Данные формы не сохраняются в localStorage.</p><p>Цель будущей обработки: ответ на запрос о строительстве. Перечень данных: имя, контакт, тип дома, площадь и комментарий. Получатели, сроки хранения, порядок отзыва согласия и окончательная редакция документа: [УКАЗАТЬ ДАННЫЕ].</p><p>Фотографии-превью загружаются с YouTube. Информация о запросах к хостингу и внешним ресурсам описывается их владельцами.</p>$(Faq $faq)</div></section>" $faq}
Write-Generated 'assets/styles.css' (Get-Content (Join-Path $root 'site/styles.css') -Raw -Encoding UTF8)
Write-Generated 'assets/app.js' (Get-Content (Join-Path $root 'site/app.js') -Raw -Encoding UTF8)
foreach($asset in @('banner.jpg','frame.jpg','roof.jpg','facade.jpg','channel-cover.jpg','construction-cc0.jpg','timber-house.jpg','barnhaus-8-9x13-5.jpg')){[IO.File]::Copy((Join-Path $root "site/assets/$asset"),(Join-Path $out "assets/$asset"),$true)}
Write-Generated '.nojekyll' ''
Write-Generated 'robots.txt' "User-agent: *`nAllow: /`nSitemap: $(Url 'sitemap.xml')`n"
Write-Generated 'sitemap.xml' ('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+(($script:urls|ForEach-Object{'<url><loc>'+ (Esc $_)+'</loc></url>'}) -join '')+'</urlset>')
if($cfg.customDomain){Write-Generated 'CNAME' $cfg.customDomain}else{$cname=Join-Path $out 'CNAME';if(Test-Path $cname){Remove-Item $cname}}
Write-Generated '404.html' "<!doctype html><html lang='ru'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width, initial-scale=1'><meta name='robots' content='noindex'><title>Страница не найдена</title><link rel='stylesheet' href='$(Link 'assets/styles.css')'></head><body><main class='wrap'><section><h1>Страница не найдена</h1><p>Проверьте адрес или откройте каталог.</p><a class='btn' href='$(Link '')'>Главная</a></section></main></body></html>"
Write-Generated 'stroitelsvo-doma/index.html' "<!doctype html><html lang='ru'><head><meta charset='utf-8'><meta name='robots' content='noindex'><link rel='canonical' href='$(Url 'stroitelstvo-doma/')'><meta http-equiv='refresh' content='0;url=$(Link 'stroitelstvo-doma/')'><title>Строительство дома</title></head><body><a href='$(Link 'stroitelstvo-doma/')'>Строительство дома</a></body></html>"
Write-Host "Generated $($script:urls.Count) pages in $out"
